# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 10
  - name: News
    url: post
    weight: 20
  - name: People
    url: people
    weight: 30
  - name: Events
    url: event
    weight: 40
  - name: Publications
    url: publication
    weight: 50
  - name: Resources
    identifier: resources
    weight: 60   
  - name: Fellowships
    parent: resources
    url: resources/fellowships
    weight: 10
  - name: Friends
    parent: resources
    url: resources/friends
    weight: 20
  - name: Internships
    parent: resources
    url: resources/internships
    weight: 30
  - name: Journals
    parent: resources
    url: resources/journals
    weight: 40
  - name: Meetings
    parent: resources
    url: resources/meetings
    weight: 50
  - name: Societies
    parent: resources
    url: resources/societies
    weight: 60
  - name: Tools
    parent: resources
    url: resources/tools
    weight: 70
  - name: Contact
    url: contact
    weight: 70